version: "3.9"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # for local development, do not need password
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always

volumes:
  pgdata:
    driver: local # using local driver for persistence of db data
